### ISSUE TITLE
Consider redefining MeterSignature

### ISSUE THREAD

**Issue by newlandsvalley** [newlandsvalley/purescript-abc-parser#47]
Currently it is ```Tuple Int Int``` but would perhaps be more useful as ```{ numerator :: Int, denominator :: Int }```. We could then have a new module ```Abc.Meter``` and move here the Meter-related functions from ```Abc.Metadata``` and add a function: ```commonTime```.

**Comment by newlandsvalley** [comment]
Fixed by db539dfb8878a19ceef69e9394414531cfb6e91c in the ps015 branch.  Now called ```TimeSignature```.

**Comment by jgarte** [comment]
Hi, can this one be closed or it requires an upgrade to PS first?

If so, I'm curious how that process looks like or how you determine when to upgrade PS without breaking changes.

**Comment by newlandsvalley** [comment]
I tend to follow the policy of only closing it once it's merged into Main/Master and as you know I had also been holding off because I was waiting for it to land in package-sets so that there was no ambiguity for anyone attempting to use it.

But the registry - package sets import has been broken for over a week now, so I'll bow to pressure and close all these parser issues that are in fact closed.  

And it is mentioned in ```breaking-changes``` for v2.0.0.

So closed now it's merged into master.

**Comment by jgarte** [comment]
No worries, I'm just scouting around for PureScript tickets I can help with ;()
